// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("app_settings")),
	appMetadata: () => typedError<AppMetaData, string>(__TAURI_INVOKE("app_metadata")),
};

/* Types */
/**
 *  Application metadata read from tauri.conf.json at startup.
 *  Displayed in window title, about dialogs, and contact sections.
 * 
 *  NOTE: short_description and long_description are temporarily
 *  commented out because tauri::Config v2 doesn't expose these
 *  fields from the config struct in a directly accessible way.
 *  Will be restored when the API supports them or when custom
 *  configuration is implemented.
 */
export type AppMetaData = {
	app_version: string,
	app_name: string,
	app_url: string,
	contacts: ContactInfo,
};

/**
 *  Persisted user settings. Read from `config.json` in
 *  `BaseDirectory::AppConfig` on startup. Falls back to
 *  defaults if the file doesn't exist yet.
 */
export type AppSettings = {
	theme: Theme,
	/**
	 *  Window resolution as (width, height). Mirrors tauri.conf.json defaults.
	 *  Future: will use WindowResolution type for validated string storage.
	 */
	resolution: [number, number],
	fullscreen: boolean,
};

/**  Contact information for the application author/maintainer. */
export type ContactInfo = {
	email: Email,
	github: string,
};

/**
 *  Validated email address. Must match `^[^\s@]+@[^\s@]+\.[^\s@]+$`.
 *  Uses OnceLock to compile regex once.
 */
export type Email = string;

/**  Theme preference matching the Tauri window's light/dark detection. */
export type Theme = "Light" | "Dark" | "System";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

