// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("app_settings")),
	appMetadata: () => typedError<AppMetaData, string>(__TAURI_INVOKE("app_metadata")),
	saveSettings: (newSettings: AppSettings) => typedError<null, string>(__TAURI_INVOKE("save_settings", { newSettings })),
};

/* Types */
/**
 *  Application metadata read from tauri.conf.json at startup.
 *  Displayed in window title, about dialogs, and contact sections.
 */
export type AppMetaData = {
	version: string,
	name: string,
	description: string,
	url: string,
	contacts: ContactInfo,
};

/**
 *  Persisted user settings. Read from `config.json` in
 *  `BaseDirectory::AppConfig` on startup. Falls back to
 *  defaults if the file doesn't exist yet.
 */
export type AppSettings = {
	theme: Theme,
	/**
	 *  Window resolution as (width, height). Mirrors tauri.conf.json defaults.
	 *  Future: will use WindowResolution type for validated string storage.
	 */
	resolution: Resolution,
	fullscreen: boolean,
};

export type ContactInfo = {
	email: Email,
	github: string,
};

export type Email = string;

export type Resolution = [number, number];

export type Theme = "Light" | "Dark" | "System";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

