version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 4
    assignees:
      - "ali-afk"
    target-branch: "main"
    labels:
      - "dependencies"
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
        update-types:
          - minor
          - patch
      misc-major:
        dependency-type: "development"
        update-types:
          - major
        exclude-patterns:
          - "svelte*"
          - "@sveltejs/*"
          - "vite*"
          - "@tauri-apps/*"
      app-major:
        update-types:
          - major
        patterns:
          - "svelte*"
          - "@sveltejs/*"
          - "vite*"
          - "@tauri-apps/*"
