// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Reads application metadata from the managed `AppMetadata` state. */
	appMetadata: () => typedError<AppMetadata, AppError>(__TAURI_INVOKE("app_metadata")),
	/**  Writes all settings to the store, overwriting the entire config. */
	writeSettings: (settings: AppSettings) => typedError<null, AppError>(__TAURI_INVOKE("write_settings", { settings })),
	/**  Writes a single setting field, leaving other fields unchanged. */
	writeSettingsField: (value: AppSettingsKey) => typedError<null, AppError>(__TAURI_INVOKE("write_settings_field", { value })),
	/**  Reads all settings from the store. Returns the full `AppSettings` struct. */
	readSettings: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("read_settings")),
	/**  Reads a single setting field by its `AppSettingsKeyKind` identifier. */
	readSettingsField: (key: AppSettingsKeyKind) => typedError<AppSettingsKey, AppError>(__TAURI_INVOKE("read_settings_field", { key })),
};

/* Types */
export type AppError = { type: "Config"; data: string } | { type: "Validation"; data: string };

/**
 *  Application metadata read from tauri.conf.json at startup.
 *  Displayed in window title, about dialogs, and contact sections.
 */
export type AppMetadata = {
	version: string,
	name: string,
	description: string,
	url: string,
	contacts: ContactInfo,
};

/**
 *  Persisted user settings. Backed by tauri-plugin-store (settings.json).
 *  Defaults written on first access via if_empty_write_default().
 */
export type AppSettings = {
	theme: Theme,
	resolution: Resolution,
	fullscreen: boolean,
};

/**
 *  A tagged union of a single setting value, used by read_settings_field
 *  and write_settings_field IPC commands. Exactly one variant is set.
 *  TS type: `{ Theme: Theme } | { Resolution: Resolution } | { Fullscreen: boolean }`.
 */
export type AppSettingsKey = ({ Theme: Theme }) & { Fullscreen?: never; Resolution?: never } | ({ Resolution: Resolution }) & { Fullscreen?: never; Theme?: never } | ({ Fullscreen: boolean }) & { Resolution?: never; Theme?: never };

/**
 *  IPC-compatible enum identifying which setting field to read/write.
 *  Use `as_ref()` to get the lowercase store key.
 *  TS type: `"Theme" | "Resolution" | "Fullscreen"`.
 */
export type AppSettingsKeyKind = "Theme" | "Resolution" | "Fullscreen";

export type ContactInfo = {
	email: Email,
	github: string,
};

export type Email = string;

export type Resolution = [number, number];

export type Theme = "Light" | "Dark" | "System";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

