// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appMetadata: () =>
		typedError<AppMetadata, string>(__TAURI_INVOKE("app_metadata")),
	writeSettings: (settings: AppSettings) =>
		typedError<null, string>(__TAURI_INVOKE("write_settings", { settings })),
	writeSettingsField: (value: AppSettingsKey) =>
		typedError<null, string>(__TAURI_INVOKE("write_settings_field", { value })),
	readSettings: () =>
		typedError<AppSettings, string>(__TAURI_INVOKE("read_settings")),
	readSettingsField: (key: AppSettingsKeyKind) =>
		typedError<AppSettingsKey, string>(
			__TAURI_INVOKE("read_settings_field", { key }),
		),
};

/* Types */
/**
 *  Application metadata read from tauri.conf.json at startup.
 *  Displayed in window title, about dialogs, and contact sections.
 */
export type AppMetadata = {
	version: string;
	name: string;
	description: string;
	url: string;
	contacts: ContactInfo;
};

/**
 *  Persisted user settings. Read from `config.json` in
 *  `BaseDirectory::AppConfig` on startup. Falls back to
 *  defaults if the file doesn't exist yet.
 */
export type AppSettings = {
	theme: Theme;
	resolution: Resolution;
	fullscreen: boolean;
};

export type AppSettingsKey =
	| ({ Theme: Theme } & { Fullscreen?: never; Resolution?: never })
	| ({ Resolution: Resolution } & { Fullscreen?: never; Theme?: never })
	| ({ Fullscreen: boolean } & { Resolution?: never; Theme?: never });

export type AppSettingsKeyKind = "Theme" | "Resolution" | "Fullscreen";

export type ContactInfo = {
	email: Email;
	github: string;
};

export type Email = string;

export type Resolution = [number, number];

export type Theme = "Light" | "Dark" | "System";

/* Tauri Specta runtime */
async function typedError<T, E>(
	result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
	try {
		return { status: "ok", data: await result };
	} catch (e) {
		if (e instanceof Error) throw e;
		return { status: "error", error: e as any };
	}
}
